optimization

diff --git a/build b/build
--- a/build
+++ b/build
@@ -5,7 +5,7 @@ make && make clean
 
 ## if compilation fails print error
 if [ $? -ne 0 ]; then
-  echo -e 'program `make` not found\r\nPlease install `make`' &>2
+  echo -e 'program `make` not found\r\nPlease install `make`' >&2
   exit 1;
 fi
 
